export const VOICE_TRANSCRIPTS_README_CONTENT = `# Voice transcripts

Each file is one transcript of an audio source (recorded dictation or imported audio file). Files are auto-generated by the Sonara extension.

## File layout

\`\`\`markdown
---
source: design-review.m4a
created: 2026-05-10T16:00:00Z
duration_sec: 2487
language: en
model: large-v3
processing_time_sec: 84.2
---

<!-- Sonara voice transcript. Format and rules: .vscode/sonara/voice-transcripts/README.md -->

## Summary

2-3 short bullets describing what the recording is about. Used by the UI list and by summary exports.

---

**Transcribed:** 2026-05-10 16:00 UTC
**Duration:** 41 min 27 sec
**Language:** en
**Model:** large-v3

[00:00:00]
Full transcript body with timecodes every minute.
\`\`\`

- Frontmatter on line 1 (no leading whitespace or comments before it).
- HTML comment after the closing \`---\`, separated by a blank line.
- One blank line between sections.
- Filename: \`YYYY-MM-DD-<kebab-source-name>.md\`. File lives directly in \`.vscode/sonara/voice-transcripts/\`.

## Frontmatter

| Field | Required | Notes |
|---|---|---|
| \`source\` | yes | original audio file name |
| \`created\` | yes | ISO timestamp of when the transcription was produced |
| \`duration_sec\` | yes | audio duration in seconds |
| \`language\` | yes | detected or forced language (\`en\`, \`uk\`, \`ru\`, ...) |
| \`model\` | yes | Whisper model name (\`large-v3\`, \`medium\`, ...) |
| \`processing_time_sec\` | no | how long the transcription took |

Unknown fields are preserved as-is.

## Rules for AI agents

- The \`## Summary\` section is the only part meant to be edited by humans or agents. Replace the placeholder with 2-3 short bullets, under 200 characters total, in the transcript language. The UI only renders the first 3 lines - anything longer is invisible.
- Do not edit the transcript body below the horizontal rule. Re-run transcription if a correction is needed.
- Do not modify frontmatter values - they describe the source, not the content.
`;
